template = "jcore1"
wpImage = "jcodigi/wordpress:latest"
wpVersion = "latest"
pluginLocal = ["loco-translate", "pattern-manager"]
pluginExclude = [
	"mainwp-child",
	"minimal-coming-soon-maintenance-mode",
	"coming-soon",
]
dbExclude = ["relevanssi"]
remoteDomain = "localhost"
localDomain = "localhost"
wpDebug = true
wpDebugLog = false
wpDebugDisplay = true
