template = "jcore3"
theme = "jcore-ilme"
wpImage = "jcodigi/wordpress:latest"
wpVersion = "latest"
pluginLocal = ["loco-translate"]
pluginExclude = ["dynamic-archive", "ruudukko"]
pluginGit = ["lohko"]
dbExclude = []
dbPrefix = "wp_"
remoteDomain = "localhost"
localDomain = "localhost"
wpDebug = true
wpDebugLog = false
wpDebugDisplay = true
